#!/bin/bash

clear
echo "🚀 Criador de projetos Next.js (React Compiler) + Tailwind + Shadcn + Biome"

# 🧠 Pergunta o nome do projeto
read -p "📦 Qual o nome do projeto? " project_name

if [ -z "$project_name" ]; then
  echo "❌ Nome do projeto não pode estar vazio."
  exit 1
fi

# 🚧 Cria o projeto base com React Compiler ativado e SEM ESLint
echo "🚀 Criando aplicação Next.js..."
pnpm create next-app@latest "$project_name" \
  --ts \
  --tailwind \
  --app \
  --src-dir \
  --no-eslint \
  --react-compiler \
  --import-alias '@/*' \
  --turbopack \
  --no

cd "$project_name" || exit 1

echo "✅ Projeto base criado com React Compiler!"

# ==========================================
# 📂 REESTRUTURAÇÃO DE PASTAS E ARQUIVOS
# ==========================================
echo "📂 Reorganizando estrutura de pastas..."

mkdir -p src/styles src/types src/utils src/lib

if [ -f "src/app/globals.css" ]; then
  mv src/app/globals.css src/styles/globals.css
  echo "moved: src/app/globals.css -> src/styles/globals.css"
fi

cat > src/types/globals.d.ts <<EOF
declare module '*.css';
EOF
echo "created: src/types/globals.d.ts"

cat > src/utils/fonts.ts <<EOF
import { Inter } from "next/font/google";

export const inter = Inter({ subsets: ["latin"] });
EOF
echo "created: src/utils/fonts.ts"

cat > src/app/layout.tsx <<EOF
import type { Metadata } from "next";
import "@/styles/globals.css";
import { inter } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={\`\${inter.className} antialiased\`}>
        {children}
      </body>
    </html>
  );
}
EOF
echo "updated: src/app/layout.tsx (imports corrigidos)"

# ==========================================
# 📦 INSTALAÇÃO E CONFIGURAÇÃO DO SHADCN UI
# ==========================================

echo "📦 Instalando dependências do Shadcn UI..."
pnpm add @shadcn/ui clsx tailwind-variants

echo "⚙️ Inicializando Shadcn UI..."
echo "🎨 Selecione a cor base (o script ajustará o css path automaticamente no components.json se necessário):"
pnpm dlx shadcn@latest init

if [ -f "components.json" ]; then
  sed -i 's|src/app/globals.css|src/styles/globals.css|g' components.json
fi

# ==========================================
# 🧹 INSTALAÇÃO E CONFIGURAÇÃO DO BIOME
# ==========================================

echo "🎯 Instalando e configurando Biome..."
pnpm add -D -E @biomejs/biome
pnpm dlx @biomejs/biome init

# Sobrescrevendo biome.json com as regras ideais para a Stack
cat > biome.json <<EOF
{
  "\$schema": "https://biomejs.dev/schemas/1.9.4/schema.json",
  "vcs": {
    "enabled": true,
    "clientKind": "git",
    "useIgnoreFile": true
  },
  "files": {
    "ignoreUnknown": false,
    "ignore": [
      ".next",
      "node_modules",
      "dist",
      "out",
      "build",
      "coverage",
      "components.json"
    ]
  },
  "formatter": {
    "enabled": true,
    "formatWithErrors": false,
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 100
  },
  "organizeImports": {
    "enabled": true
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "nursery": {
        "useSortedClasses": {
          "level": "error",
          "fix": "safe",
          "options": {
            "attributes": ["className", "class"],
            "functions": ["clsx", "cva", "tw", "twMerge", "twJoin", "tv"]
          }
        }
      }
    }
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "single",
      "jsxQuoteStyle": "double",
      "trailingCommas": "all",
      "semicolons": "always",
      "arrowParentheses": "always"
    }
  }
}
EOF

# Remover Prettier e ESLint caso o create-next-app tenha injetado algo residual
rm -f .eslintrc.json .eslintrc.js .prettierrc .prettierrc.json prettier.config.js eslint.config.mjs

# Configurações VSCode Otimizadas para Biome
mkdir -p .vscode
cat > .vscode/settings.json <<EOF
{
  "[javascript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[json]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.biome": "explicit",
    "source.organizeImports.biome": "explicit"
  }
}
EOF

cat > .vscode/extensions.json <<EOF
{
  "recommendations": [
    "biomejs.biome"
  ]
}
EOF

# Rodar a primeira formatação global
echo "✨ Rodando formatação inicial do Biome..."
pnpm dlx @biomejs/biome format --write ./src

# ==========================================
# 🧬 GIT INIT
# ==========================================

read -p "🔗 Deseja criar repositório Git local? (y/n): " git_init
if [[ "$git_init" == "y" ]]; then
  git init
  git add .
  git commit -m "feat: setup Next.js project with Biome, Tailwind and Shadcn."

  read -p "🌐 Deseja criar repositório no GitHub via CLI? (y/n): " gh_push
  if [[ "$gh_push" == "y" ]]; then
    read -p "🔐 Nome do repositório (ENTER para '$project_name'): " repo_name
    repo_name=${repo_name:-$project_name}
    gh repo create "$repo_name" --public --source=. --remote=origin --push
  fi
fi

echo -e "\n🎉 Projeto '$project_name' configurado com sucesso!"
echo -e "⚡ React Compiler e Turbopack: \033[1mATIVADOS\033[0m"
echo -e "🧹 Linter/Formatter: \033[1mBIOME (Substituindo ESLint/Prettier)\033[0m"
echo -e "\n👉 Rode com: \033[1mcd $project_name && pnpm dev\033[0m"
